services:
  postgres:
    image: postgres:latest
    container_name: postgres_photolabs_development
    environment:
      POSTGRES_USER: labber
      POSTGRES_PASSWORD: labber
      POSTGRES_DB: photolabs_development
    ports:
      - "${PGPORT}:5432"
    volumes:
      - postgres_photolabs_development_data:/var/lib/postgresql/data

volumes:
  postgres_photolabs_development_data:
